### ISSUE TITLE
[Help needed] Failed execution 

### ISSUE THREAD

**Issue by Oliver-Piorun** [viva64/pvs-studio-maven-repository#2]
Hello!

I am getting an exception when trying to run the PVS analysis.

**How to reproduce:**
- Create a clean maven project
- Add the plugin to the pom.xml
- Run "mvn pvsstudio:pvsAnalyze -X"

**Version:**
0.2

**Stack trace:**
[ERROR] Failed to execute goal com.pvsstudio:pvsstudio-maven-plugin:0.2:pvsAnalyze (default-cli) on project Test: Execution default-cli of goal com.pvsstudio:pvsstudio-maven-plugin:0.2:pvsAnalyze failed: pvs-studio.jar returned 1 code -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.pvsstudio:pvsstudio-maven-plugin:0.2:pvsAnalyze (default-cli) on project Test: Execution default-cli of goal com.pvsstudio:pvsstudio-maven-plugin:0.2:pvsAnalyze failed: pvs-studio.jar returned 1 code
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.pvsstudio:pvsstudio-maven-plugin:0.2:pvsAnalyze failed: pvs-studio.jar returned 1 code
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
**Caused by: com.pvsstudio.PvsStudioException: pvs-studio.jar returned 1 code
        at com.pvsstudio.PvsStudioInvoker.run(PvsStudioInvoker.java:92)
        at com.pvsstudio.PvsAnalyzeMojo.execute(PvsAnalyzeMojo.java:160)**
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more

I hope you can help me out. There is a **good chance** that I am doing something wrong ;)

Greetings!

**Comment by Egor18** [comment]
Hello!
This repo contains only an integration plugin for PVS-Studio Java analyzer, which has not been even released yet (so you simply don't have pvs-studio.jar).
Anyway, the message here is a bit confusing, so I'll fix it.
